language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone --depth=1 https://github.com/OCA/partner-contact.git ${HOME}/partner-contact
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
# example: dependency
  - git clone --depth=1 https://github.com/OCA/web -b ${VERSION} $HOME/web

script:
  - travis_run_tests

after_success:
  coveralls
